### ISSUE TITLE
Longest Repeated Subsequence Problem

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#10]
write Longest Repeated Subsequence Problem code using DP and also write brif description about logic

**Comment by AdiTyaa-Raj** [comment]
Hey @raunakkumarsingh , can you please assign this to me , I would love to do this!!!

**Comment by PrakritiRaw** [comment]
Hey ..!
Kindly assign this to me, i would love to contribute.
