### ISSUE TITLE
Find longest sequence formed by adjacent numbers in the matrix

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#20]
write Find longest sequence formed by adjacent numbers in the matrix Diff Utility code using DP and also write brief description about logic

**Comment by techhunter2** [comment]
I want to work on this issue please allot me this.

**Comment by raunakkumarsingh** [comment]
ya sure

**Comment by techhunter2** [comment]
I pulled a PR request for this issue please accept this.
