### ISSUE TITLE
0–1 Knapsack problem

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#22]
write 0–1 Knapsack problem code using DP and also write brief description about logic

**Comment by SOUMYADIP76** [comment]
I would like to contribute . pls assign me this issue  @raunakkumarsingh

**Comment by Titan1114** [comment]
i am interested assign this to me

**Comment by DakshVarshney1409** [comment]
I would like to contribute. Please assign me this issue @raunakkumarsingh
