### ISSUE TITLE
Maximize the Value of an Expression

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#23]
write Maximize the Value of an Expression code using DP and also write brief description about logic

**Comment by SOUMYADIP76** [comment]
I would like to contribute . pls assign me this issue  @raunakkumarsingh

**Comment by Titan1114** [comment]
i am interested assign this to me

**Comment by DakshVarshney1409** [comment]
I would like to contribute. Please assign me this issue @raunakkumarsingh
