### ISSUE TITLE
Rod Cutting Problem

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#41]
write code for Rod Cutting Problem in c++ and elaborate code properly

**Comment by DHRUVKHANDELWAL00** [comment]
hey @raunakkumarsingh , please assign this issue to me.

**Comment by DHRUVKHANDELWAL00** [comment]
Hey @raunakkumarsingh i have uploaded my code. Its working. please accept my PR under hacktoberfest.
