### ISSUE TITLE
Trapping Rain Water Problem

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#50]
write code for Trapping Rain Water Problem in c++ and elaborate code properly

**Comment by SiddhantPawar03** [comment]
> write code for Trapping Rain Water Problem in c++ and elaborate code properly

Please assign me this issue @raunakkumarsingh !

**Comment by Debayan97531** [comment]
please assign me this issue @raunakkumarsingh ..I can do it

**Comment by codemii** [comment]
Hi @raunakkumarsingh , please assign this issue to me.
