### ISSUE TITLE
Depth First Search (DFS) Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#58]
Write proper code along with Explanation

write code in algorithm folder

**Comment by Debashis08** [comment]
Please assign this task to me.

**Comment by Debashis08** [comment]
Please mention how to do the Pull Request or please mention if there are any mistakes.

**Comment by AkanshuAich** [comment]
plz assign me the task sir @raunakkumarsingh
