### ISSUE TITLE
Quicksort Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#60]
Write proper code along with Explanation

write code in algorithm folder

**Comment by ProtyayMnd50** [comment]
Can you assign it to me @raunakkumarsingh pls?

**Comment by jayprakash6547** [comment]
Hi please assign this issue to me

**Comment by AkanshuAich** [comment]
plz assign me the task sir @raunakkumarsingh .
