### ISSUE TITLE
Dijkstra’s Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#63]
Write proper code along with Explanation

write code in algorithm folder

**Comment by SiddhantPawar03** [comment]
> Write proper code along with Explanation
> 
> write code in algorithm folder

Please assign me this issue @raunakkumarsingh !

**Comment by Tushar161101** [comment]
Hey!
I'm Hacktoberfest'22 contributor .I would like to work on this issue. Please assign me this issue.

**Comment by BipinSah** [comment]
CAN YOU PLEASE ASSIGN ME THIS ISSUE @raunakkumarsingh?

**Comment by BipinSah** [comment]
Created a pull request related to this issue which you assigned me. Please review and merge it under the label hacktoberfest.
