### ISSUE TITLE
Floyd’s Cycle Detection Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#68]
Write proper code along with Explanation

write code in algorithm folder

**Comment by DHRUVKHANDELWAL00** [comment]
HEY @raunakkumarsingh please assign this issue to me.

**Comment by DHRUVKHANDELWAL00** [comment]
Hello @raunakkumarsingh , I have created a pull request for this issue. If its perfect, then please accept in under HACKTOBERFEST-accepted
