### ISSUE TITLE
Topological Sort Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#70]
Write proper code along with Explanation

write code in algorithm folder

**Comment by vibhoooo** [comment]
please assign me this issue

**Comment by Tushar161101** [comment]
Hey!
I'm Hacktoberfest'22 contributor .I would like to work on this issue. Please assign me this issue.

**Comment by Tushar161101** [comment]
Please approve my pull request.
