### ISSUE TITLE
Counting Sort Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#75]
Write proper code along with Explanation

write code in algorithm folder

**Comment by SiddhantPawar03** [comment]
> Write proper code along with Explanation
> 
> write code in algorithm folder

Hey!
I'm Hacktoberfest'22 contributor i would like to work on this issue.

**Comment by Tushar161101** [comment]
Hey!
I'm Hacktoberfest'22 contributor .I would like to work on this issue. Please assign me this issue.

**Comment by AkanshuAich** [comment]
@raunakkumarsingh  plz assign me the task . i qill be glad to work upon this.
