### ISSUE TITLE
Heap Sort Algorithm

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#76]
Write proper code along with Explanation

write code in algorithm folder

**Comment by Ak8933** [comment]
hey @raunakkumarsingh can u assign this issue to me?

**Comment by RKSingh5** [comment]
please assign this to me

**Comment by lucy2512** [comment]
I want to work on it in JAVA.Will you please assign it to me?

**Comment by AkanshuAich** [comment]
I want to work upon it . @raunakkumarsingh plz assign me the task
