### ISSUE TITLE
Longest Palindromic Subsequence using Dynamic Programming

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/Cpp_Code#9]
write Longest Common Subsequence code using DP and also write brief description about logic

**Comment by Kesav890** [comment]
can i have this issue?

**Comment by raunakkumarsingh** [comment]
ya sure

**Comment by AdiTyaa-Raj** [comment]
Hey admin, I wanted to complete this task. Can you assign this to me?
Thank you
